apiVersion: v1
kind: Service
metadata:
  name: redmine-mysql
  labels:
    app: redmine
spec:
  ports:
    - port: 3306
  selector:
    app: redmine
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: redmine-mysql
  labels:
    app: redmine
spec:
  selector:
    matchLabels:
      app: redmine
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redmine
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        volumeMounts:
        - name: mysql-config
          mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
          subPath: mysqld.cnf
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: local-pvc-redmine-mysql
      - name: mysql-config
        configMap:
          name: configmap-mysql-redmine
          items:
            - key: mysqld.cnf
              path: mysqld.cnf

