apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-sc-redmine-mysql
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-sc-redmine-mysql
  local:
    path: /mnt/redmine-mysql # create folder
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-41-61       
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-redmine-mysql
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc-redmine-mysql
  resources:
    requests:
      storage: 3Gi
