apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-sc-redmine
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-redmine
  labels:
    app: redmine
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-sc-redmine
  local:
    path: /mnt/redmine # create dir and chmod 777
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-45-213      
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-redmine
  labels:
    app: redmine
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-sc-redmine
  resources:
    requests:
      storage: 5Gi
