---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
  template:
    metadata:
      labels:
        app: redmine
    spec:
      containers:
        - name: redmine
          image: redmine:tag
          ports:
          - containerPort: 80
            name: redmine
          volumeMounts:
            - name: redmine-data
              mountPath: /var/www
          env:
            - name: ENV_VAR
              value: value
            - name: OTHER_VAR

      volumes:
        - name: redmine-data

