---
kind: Service
apiVersion: v1
metadata:
  name: redmine-lb
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    # service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/wp-login.php"
spec:
  type: LoadBalancer
  selector:
    app: redmine
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
