apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-wp
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-local-wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-wp
  local:
    path: /mnt/wordpress # create dir and chmod 777
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ip-172-31-41-61       
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-local-wordpress
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage-wp
  resources:
    requests:
      storage: 5Gi
