#!/bin/sh

echo "<h1>It PassEnv ${DEVOPS}</h1> " >> /var/www/localhost/htdocs/index.shtml
#!/usr/bin/perl
#use strict;
#use warnings;
 
#print "Content-type: text/html\n\n";
 
#print "Hello World! $ENV{$DEVOPS}";
