node {
  stage('Builddd'){
    checkout scm
    sh 'cat jenkins/Jenkinsfile'
    sh 'pwd'
    sh 'cat jenkins/Dockerfile'
    sh 'docker ps'
    sh 'docker build . -t jnknspipehttpd'
    sh 'docker images'
  }
}
