node {
  stage('Builddd'){
    checkout scm
    sh 'cd jenkins'
    sh 'pwd'
    sh 'cat jenkins/Dockerfile'
    sh 'docker ps'
    sh 'docket build . -t jenkinspipehttpd'
    sh 'docker images'
  }
}
