---
# tasks file for deploy_mysql

- name: InstallEcho
  shell: echo helloworld

- name: pullImage
  docker_image:
    name: mysql:5.7.34
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: start mysql container
  docker_container:
    name: hello-mysql
    image: mysql:5.7.34
    state: started
    env:
        MYSQL_ROOT_PASSWORD={{ root_db_pass }}
    ports:
      - "3306:3306"
  become: yes
